import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("skills/:slug", "routes/skill-detail.tsx"),
  route("profile", "routes/profile.tsx"),
  route("settings", "routes/settings.tsx"),
  route("docs", "routes/docs.tsx"),
  route("docs/agents", "routes/docs-agents.tsx"),
  route("docs/api", "routes/docs-api.tsx"),
  route("leaderboard", "routes/leaderboard.tsx"),
  route("api/auth/*", "routes/auth-catchall.tsx"),
  route("api/search", "routes/api.search.ts"),
  route("api/leaderboard", "routes/api.leaderboard.ts"),
  route("api/admin/seed", "routes/api.admin.seed.ts"),
  route("api/admin/recompute", "routes/api.admin.recompute.ts"),
  route("api/skills/register", "routes/api.skill-register.ts"),
  route("api/skills/:slug", "routes/api.skill-detail.ts"),
  route("api/skills/:slug/rate", "routes/api.skill-rate.ts"),
  route("api/skills/:slug/review", "routes/api.skill-review.ts"),
  route("api/skills/:slug/favorite", "routes/api.skill-favorite.ts"),
  route("api/skills/:slug/install", "routes/api.skill-install.ts"),
  route("api/skills/:slug/vote", "routes/api.skill-vote.ts"),
  route("api/report", "routes/api.usage-report.ts"),
  route("api/user/api-keys", "routes/api.user-api-keys.ts"),
  route("api/user/interactions", "routes/api.user-interactions.ts"),
  route("*", "routes/$.tsx"),
] satisfies RouteConfig;
